WEBDRIVER:
 resolution: 1920x1080 # The resolution of the webdriver
 headless: True # run the webdriver in the headless mode
 refresh_wait: 5 # the wait time after each page refresh
 initial_wait: 20 # the wait time for page loading
 switch_wait: 3 # the wait time for switch between buttun elements in page
 zoom_wait: 3 # the wait time for zooming
 retry: 5 # retry counts for the failure of loading page
 ua: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/71.0.3578.98 Safari/537.36
 load_image: False
Task:
 # The delay time of each sub-process
 delay_max: 5
 delay_min: 3
 # The main process is stuck when the sub-process is on-going, should consider it
 schedule: 23



